### ISSUE TITLE
Grounder's lift plan implementation not finished

### ISSUE THREAD

**Issue by fteicht** [aiplan4eu/unified-planning#113]
Hi all,

When trying to use the `rewrite_back_plan_function` returned by the Grounder's constructor, a `NotImplemented` exception is raised by the following line from `unified-planning`:

https://github.com/aiplan4eu/unified-planning/blob/223a23d2dafe6f60dd1d07ed001c2c70ef94eccd/unified_planning/solvers/grounder.py#L97

Should I understand that the `rewrite_back_plan_function` is not yet usable?

**Comment by alvalentini** [comment]
This issue is due because you are not passing a `Plan` object (e.g. `SequentialPlan`, `TimeTriggeredPlan`) to the `rewrite_back_plan_function`. But we can probably raise a more explanatory exception.

I checked your code and I noticed that you are passing a list of `Action`, you have to convert it into a `SequentialPlan`.

**Comment by mikand** [comment]
@fteicht It should as easy as doing `SequentialPlan([ActionInstance(x) for x in plan])` before line 110 https://github.com/aiplan4eu/up-skdecide/blob/master/up_skdecide/solver.py#L110

**Comment by fteicht** [comment]
Thanks @alvalentini and @mikand ! Your proposition did the trick.
One thing I'd like to understand: why doesn't the grounded problem's `actions()` method does not return a list of ActionInstantiation objects but a list of InstantaneousAction objects? I thought that the grounded problem would only consist in instantiated actions.

**Comment by fteicht** [comment]
>  But we can probably raise a more explanatory exception.

Indeed, I think a `RuntimeError` would probably make sense because a `NotImplementedError` usually refers to a feature or a specialised method to be implemented by the library's developers, whereas here it is a use error frm the user of the method.

**Comment by mikand** [comment]
@fteicht In the UP we distinguish (admittedly in a quite strict way) between "actions of the problem" that are the possible transitions (with or without parameters) in the problem formulation and "plan actions" that are elements of a plan. The former are modeled in a class hierarchy rooted in the `Action` class, and `InstantaneousAction` is one of these. A plan action is called `ActionInstance` because we might have more than one instance of the same action in a plan (e.g. I perform two times an activity that increments a number).

Does it make sense?


@alvalentini Indeed we might raise a `NotImplementedError` is the input plan is an instance of `Plan` but not a recognized plan type (meaning we lack some internal code as Florent was saying), while `ValueError` could be a fitting exception if the user enters a non-Plan object.
