### ISSUE TITLE
How to check the applicability of an action at a given state and apply it

### ISSUE THREAD

**Issue by TheAeryan** [aiplan4eu/unified-planning#114]
### User Story
As an **AI researcher** I want to use UP in my research project to:

1.  **Check action applicability**: given the current state _s0_, check if a **lifted** action _a_ can be applied at _s0_ (their preconditions are met at that state) or not. Another option is to use a method to obtain all the possible instantations of _a_ at _s0_ (i.e., obtain the grounded actions corresponding to the lifted action _a_) and, then, use another method to check the applicability of each grounded action at _s0_.

2. **Apply an action to the state**: after checking that _a_ is applicable, obtain the grounded action _a\_g_ by manually selecting the object to instantiate each parameter on and, then, obtain the next state _s1_ that results from applying _a\_g_ at _s0_. Ideally, this process would support PDDL extensions like :exists, :forall and :when.

In case this functionality is not implemented yet and there are no intentions to do so in the next few days, I would really appreciate some guidance for implementing such functions myself.

### Acceptance Criteria

- [ ] Action applicability implemented.
- [ ] Action transition implemented.

**Comment by alexander-sung** [comment]
Great, I have similar user stories in mind. I would just split them into two issues/user stories and address them separately. With regard to the first part, here's my version:

### User Story
As a **UP user** I want to `get_actual_preconditions()` from an `ActionInstance` to verify that a planned action can be executed when it's its turn.

**Rationale**: The situation when I get a plan of actions will change over time due to applying these actions but potentially also due to external factors. When I'm about to execute the next planned action, I want to make sure its preconditions are fulfilled as assumed during planning. In my application domain when not using AI planning, I would implement these checks on some sort of state variables. When using AI planning, I need these checks as fluents for planning. Since it is not simple to in general deduce fluents from state conditions but, the other way round, it is easy to map to a state variable check when given a fluent, it makes sense to only implement these checks as UP fluents and also check them during run time.

This information is available from what I see since you can retrieve the action definition from an `ActionInstance`, and from the action its preconditions. Using the `ActionInstance`'s `actual_parameters()` it's possible to determine the actual preconditions at execution time. A bit more tricky would be the mapping of parameters to the different signatures of preconditions, so a direct support of this functionality from UP would be potentially more efficient and avoid redundant manual implementations.

From discussions with Oscar I learned the UP team is considering preconditions and effects as part of the returned plan, so this is very related. With this user story, I want to emphasize the demand and present the rationale from a user's point of view. Perhaps you have a more comprehensive solution in mind, which would be welcome even more.

### Acceptance Criteria

- [ ] Decide whether providing such functionality as part of UP makes sense.
- [ ] If so, provide a `ActionInstance.get_actual_preconditions()` method or similar.
- [ ] Optionally, consider related functionality like `get_actual_effects()` for completeness of the interface.

**Comment by TheAeryan** [comment]
I totally agree with the idea of splitting my issue into two distinct user stories.

In the end, I have opted for using a different software for my project as UP is in an early stage and does not suit my current needs. Nevertheless, I look forward to seeing the development of this project!

**Comment by Framba-Luca** [comment]
Hi @TheAeryan and @alexander-sung , sorry for the late response.

I think the [SequentialSimulator](https://unified-planning.readthedocs.io/en/latest/api_ref.html#unified_planning.engines.SequentialSimulator) fits this use-case, right?

Let me know if it does what you need it to or not.

**Comment by alexander-sung** [comment]
Hello @Framba-Luca, thanks for the response still. Sebastian was already looking into the SequentialSimulator from our side, so that should be fine. Let's discuss details in our further meetings.

**Comment by TheAeryan** [comment]
Hi @Framba-Luca , thanks for the response. However, I no longer need this functionality, as I have implemented it myself as part of [Lifted PDDL](https://github.com/AI-Planning/lifted-pddl).
