### ISSUE TITLE
Unused fluents

### ISSUE THREAD

**Issue by AfkValerik** [aiplan4eu/unified-planning#208]
Up throws errors regarding uninitialized fluents, even though they are not used.

`self = problem name = pfile01

types = [place, market - place, depot - place, locatable, truck - locatable, goods - locatable...:= false
  at(truck0, market5) := false
]

goals = [
  ((request(goods0) <= bought(goods0)) and at(truck0, depot0))
]

fluent = drive-cost(market1, market1)

    def initial_value(self, fluent: Union['up.model.fnode.FNode', 'up.model.fluent.Fluent']) -> 'up.model.fnode.FNode':
        '''Gets the initial value of the given fluent.'''
        fluent_exp, = self._env.expression_manager.auto_promote(fluent)
        for a in fluent_exp.args:
            if not a.is_constant():
                raise UPExpressionDefinitionError(f'Impossible to return the initial value of a fluent expression with no constant arguments: {fluent_exp}.')
        if fluent_exp in self._initial_value:
            return self._initial_value[fluent_exp]
        elif fluent_exp.fluent() in self._fluents_defaults:
            return self._fluents_defaults[fluent_exp.fluent()]
        else:
>           raise UPProblemDefinitionError('Initial value not set!')
E           unified_planning.exceptions.UPProblemDefinitionError: Initial value not set!

../../../../.local/lib/python3.8/site-packages/unified_planning/model/problem.py:267: UPProblemDefinitionError`

Below an example of the Pddl files from which the error was generated
[Pddl files.zip](https://github.com/aiplan4eu/unified-planning/files/9110399/Pddl.files.zip)

**Comment by mikand** [comment]
We decided not to support (for the moment at least) the `undefined` value semantics adopted by PDDL. Hence, you need to specify a concrete initial value for all the ground fluents. 

Note, however, that the PDDL parser is capable of reading problems with incomplete initializations, but then some code (and care) is needed to set concrete initial values.

For example,  one might set the default initial value for uninitailized fluents to -1 as follows , but then also suitable preconditions in the problem are needed to maintain the correct semantics.
```python
problem = parser.parse_problem(...)
# This will avoid the error, but care should be taken to maintain the problem semantics,
# possibly modifying/adding conditions in the problem 
problem.fluents_defaults[problem.fluent("drive-cost")] = Int(-1) 
```

In general, getting a (possibly more explicit) error is the expected behavior here.
