### ISSUE TITLE
How to obtain applicable actions

### ISSUE THREAD

**Issue by TheAeryan** [aiplan4eu/unified-planning#250]
Hi,

I am trying to obtain the **applicable actions** for a given problem, i.e., those actions for which their preconditions are met at the initial state. Right now, I have used the method you show in the notebook `Planning_engine_demo.ipynb` (see code below). This code works but is incredibly slow. The grounding takes around 40 seconds (for a PDDL problem of the logistics domain which contains 60 objects) which I suppose it's not that slow, but testing the applicability of each grounded action takes around 2 seconds per action. Since my problem has 15700 different ground actions, obtaining a list with all the applicable actions would take more than 8 hours!

Here is my code:

```
import unified_planning as up
import unified_planning.engines as engines
from unified_planning.shortcuts import *
from unified_planning.io import PDDLReader, PDDLWriter
import time

reader = PDDLReader()
problem = reader.parse_problem('logistics-domain.pddl', 'logistics-problem.pddl')

# >> Obtain applicable ground actions as https://github.com/aiplan4eu/unified-planning/blob/master/notebooks/Planning_engine_demo.ipynb

start = time.time()
env = problem.env
with env.factory.Compiler(problem_kind=problem.kind, compilation_kind=engines.CompilationKind.GROUNDING) as grounder:
	grounding_result = grounder.compile(problem, engines.CompilationKind.GROUNDING)
	grounded_problem = grounding_result.problem

end = time.time()
print("Grounding time:", end-start, "s") # 42 seconds for a problem with 67 objects

actions = list(grounded_problem.instantaneous_actions)
print("Num ground actions:", len(actions)) # 15700 ground actions

# Obtain applicable actions
applicable_actions = []
plan = up.plans.SequentialPlan([])

with env.factory.PlanValidator(name='sequential_plan_validator') as pv:
	for a in actions:
		start = time.time()
		ai = up.plans.ActionInstance(a)
		plan.actions.append(ai)

		if pv.validate(grounded_problem, plan): # Action is valid
			applicable_actions.append(a)

		plan.actions.pop()
		end = time.time()

		print("> Time for testing applicability of last action:", end-start, "s") # 2 seconds aprox.
```

Do you know of a more **efficient method for obtaining a list with the applicable actions at a given state**?

**Comment by alvalentini** [comment]
Hi @TheAeryan, can you attach the example problem files please?

**Comment by TheAeryan** [comment]
@alvalentini Yes, of course!

**Domain file:** [logistics-domain.pddl.txt](https://github.com/aiplan4eu/unified-planning/files/9851234/logistics-domain.pddl.txt)

**Problem file:** [logistics-problem.pddl.txt](https://github.com/aiplan4eu/unified-planning/files/9851235/logistics-problem.pddl.txt)

**Comment by Framba-Luca** [comment]
Hi @TheAeryan , for your problem the [SequentialSimulator](https://unified-planning.readthedocs.io/en/latest/api_ref.html#unified_planning.engines.SequentialSimulator) looks way better than the `PlanValidator`. 

Sadly we don't have a notebook on how to use the `Simulator` yet, but the `get_applicable_events` method will give you all the [events](https://unified-planning.readthedocs.io/en/latest/api_ref.html#unified_planning.engines.InstantaneousEvent) that are applicable in the given [state](https://unified-planning.readthedocs.io/en/latest/api_ref.html#unified_planning.model.UPCOWState).

For your specific use-case I don't know if getting the applicable `Event` is enough. An `InstantaneousEvent` is basically the same of a grounded `InstantaneousAction`; if you want to keep simulating you can use it, but if you just need to check the applicability of a single action, what I suggest is the following:

- Ground the Problem (as you are already doing).
- Create the initial state (with `initial_state = up.model.UPCOWState(grounded_problem.initial_values)`)
- Get the Simulator from the factory with the grounded problem as input (use the [Simulator](https://unified-planning.readthedocs.io/en/latest/api_ref.html#unified_planning.engines.Factory.Simulator) Operation Mode).
- Iterate over the grounded problem actions.
- For each action get the corresponding `InstantaneousEvent` (with the `events = simulator.get_events(action, [])` method) (NOTE: If the problem is grounded, here you must pass an empty `tuple` or an empty `list`, in the end I will explain why).
- For the given `InstantaneousEvent` check the applicability in the initial state (with `applicable = simulator.is_applicable(events[0], initial_state)`) (NOTE: `events` is a `List`, but for the `InstantaneousActions` it contains only 1 item).
- The `applicable` variable contains your answer for the current action. 

Notes:
- You don't need to ground the problem before, the `SequentialSimulator` already grounds it on demand. But if the problem is not grounded, the second parameter of the `simulator.get_events` function must be a `list` (or a `tuple`) of the parameters you want to use to ground the given action.
- If you want to simulate more steps, check the `apply` and `apply_unsafe` methods
- If for some reason you want to know which specific precondition is preventing the action applicability, you can use the [get_unsatisfied_conditions](https://unified-planning.readthedocs.io/en/latest/api_ref.html#unified_planning.engines.SequentialSimulator.get_unsatisfied_conditions) method.



Since this is a library that should be accessible to everyone, we are putting a lot of effort in trying to document it as thoroughly as possible. So any feedback about the documentation, API usage and efficiency of the code is very very welcome!

Let me know if this works for you,
Luca

**Comment by Framba-Luca** [comment]
I tried the efficiency of what I suggested and it really improves, here is the python code I used:
[pddl_testing.py.txt](https://github.com/aiplan4eu/unified-planning/files/9860999/pddl_testing.py.txt)

**Comment by TheAeryan** [comment]
I tried your code on my computer and running times are: 90 seconds in total, around 40s for grounding and 50s for obtaining applicable actions.
This is still too much. The reason is that, in my project, I need to repeatedly obtain the list of applicable actions several times (around 60) for a given problem. Therefore, I would spend 40s (we only ground once) + 50s*60 = 3040s, which is more than 50 minutes. This is a big improvemente when compared to the runtime of my code, but it is still far from enough.
Automated planners need to perform this operation (i.e., obtain the list of applicable actions) many times during the planning process. This means that the efficiency of the code is not enough for it to be used to program an automated planner (like the ones you provide as engines).
State-of-the-art planners use different algorithms and data structures for obtaining the applicable actions in an efficient manner. I don't know much about the topic, but some examples include match trees (switch graphs), join programs, etc. **Are these options available in the unified-planning code and, if not, will they be added in the future?**

**Comment by alvalentini** [comment]
@TheAeryan There was an inefficiency in the code of the SequentialSimulator, I fixed it in 5b8edcece7fa788f24740c750ede2a0c94c61547. Now the code provided by @Framba-Luca should be much more faster (on my PC ~1 second). Is this enough for your project?

Of course it is not as efficient as the successor function of a planning engine, but it is not its purpose.

**Comment by TheAeryan** [comment]
@alvalentini Just tested the new version. The time of grounding remains the same (around 50s), but the applicability check time has been reduced x10, so now obtaining the list of applicable actions only takes 5s.

The time for testing action applicability is low enough for my project, the "bottleneck" now is the time needed to ground the actions. However, I understand that this is not a fault of the code but that, in the general case, grounding the action schemas is a process that takes a lot of time (regardless of the planner used). Maybe the efficiency could be increased by using less "encapsulation" (i.e., fewer classes and more primitive data structures), but I understand that this is outside the scope of the project.

A possible workaround for this would be to obtain the applicable actions without grounding first, as **lifted planners** do (e.g., https://github.com/abcorrea/powerlifted). Do you have plans to implement this type of lifted reasoning? If not, maybe I can use the code in its current state (grounding + action applicability) and, in the future, implement these algorithms myself (action applicability without grounding) and add a pull request. What are your thoughts about this?

**Comment by Framba-Luca** [comment]
@TheAeryan At the moment pyperplan is automatically selected for your problem kind. But it is not the most efficient grounder for your kind of problem. I suggest you to use the tarski grounder:
 `with Compiler(name = "tarski_grounder", compilation_kind=CompilationKind.GROUNDING) as grounder:`

With tarski grounder the total execution time on my computer is reduced to approx 2 seconds!

In the future we will improve the automatic selection of the engines; in order to use the best one for the given problem.

**Comment by TheAeryan** [comment]
@Framba-Luca when in my code I change the line `with Compiler(problem_kind = problem.kind, compilation_kind=CompilationKind.GROUNDING) as grounder:` for `with Compiler(name = "tarski_grounder", compilation_kind=CompilationKind.GROUNDING) as grounder:`, I get the error `unified_planning.exceptions.UPNoRequestedEngineAvailableException`.

I tried to install the tarski dependency with `pip install unified-planning[tarski]` but the problem still persists.

**Comment by Framba-Luca** [comment]
@TheAeryan Which operative system are you using?

**Comment by TheAeryan** [comment]
@Framba-Luca I am using Windows 11.

**Comment by TheAeryan** [comment]
@Framba-Luca I see. For now, I think I will implement myself the applicability check method used in **Powerlifted** (https://github.com/abcorrea/powerlifted), which does not need to ground the actions.
@alvalentini I will probably release my code as a command-line utility which can be called as `compute_applicable domain.pddl problem.pddl` and will output the list of applicable ground actions at the initial state of `problem.pddl`, like `(move locA locB) (move locA locC) ...` Do you think this could be useful for unified-planning?

**Comment by alvalentini** [comment]
@TheAeryan Having an efficient function to compute the list of applicable ground actions at a given state it could be really useful for the unified-planning to improve the performance of the simulator. 

However having this functionality as a command-line utility that works through PDDL files, it is not the best way to integrate it in the unified-planning. It would be great if you could create a PR that implement this functionality inside the unified-planning using its data structures. Of course we can give you all the needed support to do that.

**Comment by TheAeryan** [comment]
@alvalentini I see. Right now, that would be a lot of work since I use my own data structures and I am not familiar with the inner workings of unified-planning. I can leave that for the future or provide you with the code (which is a very minimal and easy-to-understand Python implementation) in case you want to integrate it with unified-planning (as you did with pyperplan, tarski, etc.)

**Comment by TheAeryan** [comment]
I have finished implementing my code. It is called **Lifted Pddl" and is provided as a [Python package](https://pypi.org/project/lifted-pddl). It can be used both within Python (`import lifted_pddl`) and also via CLI.
As I said, right now I can't integrate it with unified-planning, but I would like to in the future, once it has better documentation (and I have more spare time). If someone else would like to perform this integration, just let me know :)
For now, I close the issue. Thank you very much for your help, @Framba-Luca and @alvalentini.
