### ISSUE TITLE
Missing precondition.

### ISSUE THREAD

**Issue by MFaisalZaki** [aiplan4eu/unified-planning#471]
For some reason, the `preconditions` list does not contain the predicate precondition for an action having both arithmetic and boolean conditions.
 
I have tested this on the `fo-farmland` [domain.zip](https://github.com/aiplan4eu/unified-planning/files/12295355/domain.zip), and the action `move-by-car` has a precondition call `adj` which is not presented in the list of preconditions:
<img width="1156" alt="Screenshot 2023-08-08 at 8 51 08 PM" src="https://github.com/aiplan4eu/unified-planning/assets/9129265/e3b03a18-60e7-47dc-a372-a55bb01db6e9">

To reproduce, I sort the actions alphabetically:
```
task = PDDLReader().parse_problem('domain.pddl', 'instance_1.pddl')
with Compiler(problem_kind=task.kind, compilation_kind=CompilationKind.GROUNDING) as grounder:
            ground_problem.actions = grounder.compile(self.task, compilation_kind=CompilationKind.GROUNDING).problem
actionlist = sorted([action for action in ground_problem.actions], key=lambda x: x.name)
for action in actionlist:
    for pre in action.preconditions:
        print(pre)
```

**Comment by mikand** [comment]
Hello @MFaisalZaki!

Since you are grounding the problem, the action you are inspecting in the screenshot is `move_by_car(farm0, farm1)` (i.e. the grounding of your action where `?f1=farm0` and `?f1=farm1`). The condition `adj(?f1, ?f2)` present in the original domain is thus simplified away because `adj(farm0, farm1)` is true in the initial state and no action modify the `adj` predicate.

If you inspect the `task` before grounding you'll see that the precondition is there (as no simplification is possible).

**Comment by mikand** [comment]
BTW, also the `(not (= ?f1 ?f2))` part of the precondition is removed because it simplifes to `true`

**Comment by MFaisalZaki** [comment]
Thanks for clarifying that.
