### ISSUE TITLE
Grounding not working properly in docker image

### ISSUE THREAD

**Issue by MFaisalZaki** [aiplan4eu/unified-planning#483]
For some reason, the optimisation phase when grounding problems is not working properly when using UP inside a docker image.

A simple test case is to ground the rover problem and dump the preconditions and effects into a JSON file inside a docker container and local machine. This archive contains two [json-files.zip](https://github.com/aiplan4eu/unified-planning/files/12489133/json-files.zip) one was generated from a local machine, while the other using a docker image. 

You can notice inside the `actions-docker.json` the `channel_free` variable is presented in the effect having both values `true` and `false`, which is not the case in `actions-local.json`. Based on [this discussion](https://github.com/aiplan4eu/unified-planning/issues/471#issue-1841988440), this predicate should have been removed, but this did not happen.

Here is the [test script](https://github.com/aiplan4eu/unified-planning/files/12484444/test-case.zip) I used to generate the JSON files. You only need to run it inside a docker container and on your local machine. Also, I have used the latest commit, `d01c9fe`.

**Comment by Framba-Luca** [comment]
Hi @MFaisalZaki , can I get more info? 

In particular:
- the code you used to generate the docker image
- the UP version used in the docker image (I see you used the last commit on your machine, is it the same in the docker image?)
- the grounder used in both examples (you can get it with `print(grounder.name)`)
- anything else you think might be helpful

Thanks!

**Comment by MFaisalZaki** [comment]
Hi @Framba-Luca 

The code is the same. I have run the code on my local machine and on a docker image and dumped both files. 

Also, I have used the same commit on both the local machine and the docker image.

**Comment by MFaisalZaki** [comment]
Hi @Framba-Luca, 

Apparently I forgot to install the engines, after I installed them everything works prefect. I was hopping if UP can have list a warning message to say that there is no engines installed.

Thanks again for your help. Please feel free to close the issue.

**Comment by Framba-Luca** [comment]
The issue is more subtle.

There is a grounder installed, which is the default one and does an exhaustive grounding. When you install the engines they are used for the grounding, while when they are not installed the default one is used. So, there is a grounding bug in the default grounder but not in the other ones.

Thanks for the report!

**Comment by Framba-Luca** [comment]
So @MFaisalZaki I looked a bit into this:

There are no problems with the grounding/internal grounder; even the solution with `channel_free := true` and `channel_free := false` is a correct representation. It follows the `delete-before-add` semantic (discussion [here](https://github.com/aiplan4eu/unified-planning/discussions/191), so, after the application, the `channel_free := true` statement prevails on the other; as it is applied after.

For clarity, `channel_free := false` is a delete effect, `channel_free := true` is an add effect).

Other grounding algorithms decide not to add those actions to the grounded actions section because of their pruning. You might also want to play around with other grounders to see the number of actions you get in the end.
