### ISSUE TITLE
Implement a unified_planning binding in scikit-decide

### ISSUE THREAD

**Issue by mikand** [aiplan4eu/unified-planning#95]

**Comment by mikand** [comment]
@fteicht This is almost done, right?
I think the only thing that is missing is to create a PyPI package for up-scikit-decide and to add it as a default solver in the UP.

Another thing FYK: in #156 we are creaing a simulator operation mode for the UP, this might greatly simplify yor code,

**Comment by fteicht** [comment]
@mikand I think the basic implementation is indeed almost done apart from the actions you mention.
However, I noticed that the grounding of the problem is killing the approach on large problems: it takes hours before `up-skdecide` could even start solving the problem.
To solve realistic instances, `up` should provide a lazy grounding mechanism where only the applicable actions are grounded on the fly for the current state (meaning that the feasible object instantiations of each action should be tested on the fly when evaluating each action's precondition formula).
Or can you think of another solution to this grounding issue?

**Comment by fteicht** [comment]
To add a bit more on my previous comment: the approach I am describing proved to be effective for large Probabilistic PDDL benchmark. I implemented it and successfully tested it, see [there](https://github.com/fteicht/ppddl-planner/blob/8d00c4605658fc9cc1e8d442f9d32dd7b92e893f/sdk/mdpsim-2.2-ftk/actions.cc#L200) and [there](https://github.com/fteicht/ppddl-planner/blob/8d00c4605658fc9cc1e8d442f9d32dd7b92e893f/sdk/mdpsim-2.2-ftk/formulas.cc) for how the `holds` formula is actually evaluated for each possible formula class.
